//
//  ShowPersonPresenter.swift
//  VipExample
//
//  Created by Thiago Valente on 26/09/19.
//  Copyright (c) 2019 Thiago Valente. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPersonPresentationLogic {
	func presentSomething(response: ShowPerson.Something.Response)
}

class ShowPersonPresenter: ShowPersonPresentationLogic {
	weak var viewController: ShowPersonDisplayLogic?

	//MARK: Do something
	func presentSomething(response: ShowPerson.Something.Response) {
		let viewModel = ShowPerson.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
