//
//  ShowPersonInteractor.swift
//  VipExample
//
//  Created by Thiago Valente on 26/09/19.
//  Copyright (c) 2019 Thiago Valente. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPersonBusinessLogic {
	func doSomething(request: ShowPerson.Something.Request)
}

protocol ShowPersonDataStore {
	//var name: String { get set }
}

class ShowPersonInteractor: ShowPersonBusinessLogic, ShowPersonDataStore {
	var presenter: ShowPersonPresentationLogic?
	var worker: ShowPersonWorker?
	//var name: String = ""

	//MARK: Do something
	func doSomething(request: ShowPerson.Something.Request) {
		worker = ShowPersonWorker()
		worker?.doSomeWork()

		let response = ShowPerson.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
