//
//  ShowPersonViewController.swift
//  VipExample
//
//  Created by Thiago Valente on 26/09/19.
//  Copyright (c) 2019 Thiago Valente. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowPersonDisplayLogic: class {
	func displaySomething(viewModel: ShowPerson.Something.ViewModel)
}

class ShowPersonViewController: UIViewController, ShowPersonDisplayLogic {
	//MARK: Property
	var interactor: ShowPersonBusinessLogic?
	var router: (NSObjectProtocol & ShowPersonRoutingLogic & ShowPersonDataPassing)?

	//MARK: View lifecycle
	override func viewDidLoad() {
		super.viewDidLoad()
		doSomething()
	}

	//MARK: Setup
	private func setup() {
		let viewController = self
		view = ShowPersonView()
		let interactor = ShowPersonInteractor()
		let presenter = ShowPersonPresenter()
		let router = ShowPersonRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}

	//MARK: Do something
	func doSomething() {
		let request = ShowPerson.Something.Request()
		interactor?.doSomething(request: request)
	}

	func displaySomething(viewModel: ShowPerson.Something.ViewModel) {
		//nameTextField.text = viewModel.name
	}
}
