//
//  ShowPersonRouter.swift
//  VipExample
//
//  Created by Thiago Valente on 26/09/19.
//  Copyright (c) 2019 Thiago Valente. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowPersonRoutingLogic {
	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowPersonDataPassing {
	var dataStore: ShowPersonDataStore? { get }
}

class ShowPersonRouter: NSObject, ShowPersonRoutingLogic, ShowPersonDataPassing {
	weak var viewController: ShowPersonViewController?
	var dataStore: ShowPersonDataStore?

	//MARK: Routing
//	func routeToSomewhere(segue: UIStoryboardSegue?) {
//		if let segue = segue {
//			let destinationVC = segue.destination as! SomewhereViewController
//			var destinationDS = destinationVC.router!.dataStore!
//			passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//		} else {
//			let storyboard = UIStoryboard(name: "Main", bundle: nil)
//			let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//			var destinationDS = destinationVC.router!.dataStore!
//			passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//			navigateToSomewhere(source: viewController!, destination: destinationVC)
//		}
//	}
//
//	//MARK: Navigation
//	func navigateToSomewhere(source: ShowPersonViewController, destination: SomewhereViewController) {
//		source.show(destination, sender: nil)
//	}
//
//	//MARK: Passing data
//	func passDataToSomewhere(source: ShowPersonDataStore, destination: inout SomewhereDataStore) {
//		destination.name = source.name
//	}
}
