//
//  ListPersonWorker.swift
//  VipExample
//
//  Created by Thiago Valente on 26/09/19.
//  Copyright (c) 2019 Thiago Valente. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListPersonWorker {
    func fetchPeople(completion: ([Person]) -> Void) {
        let person1 = Person(name: "Valente", salary: 800)
        let person2 = Person(name: "Mangueira", salary: 20000)
        let person3 = Person(name: "Bruno", salary: 3000)
        completion([person1, person2, person3])
	}
}
