//
//  ListPersonPresenter.swift
//  VipExample
//
//  Created by Thiago Valente on 26/09/19.
//  Copyright (c) 2019 Thiago Valente. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPersonPresentationLogic {
    func presentFetchedPeople(response: ListPeople.FetchPeople.Response)
}

class ListPersonPresenter: ListPersonPresentationLogic {

    weak var viewController: ListPersonDisplayLogic?

    //MARK: Do something
    func presentFetchedPeople(response: ListPeople.FetchPeople.Response) {
        var displaydPeople: [ListPeople.FetchPeople.ViewModel.DisplayedPerson] = []
        for person in response.people {
            let name = person.name
            let salary = String(format: "%.2f", person.salary)
            let displayedPerson = ListPeople.FetchPeople.ViewModel.DisplayedPerson(
                name: name,
                salary: salary
            )
            displaydPeople.append(displayedPerson)
        }
        let viewModel = ListPeople.FetchPeople.ViewModel(displayedPeople: displaydPeople)
        viewController?.displayFetchedPeople(viewModel: viewModel)
    }
}
