//
//  ListPersonInteractor.swift
//  VipExample
//
//  Created by Thiago Valente on 26/09/19.
//  Copyright (c) 2019 Thiago Valente. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPersonBusinessLogic {
    func fetchPeople(request: ListPeople.FetchPeople.Request)
}

protocol ListPersonDataStore {
    //var name: String { get set }
}

class ListPersonInteractor: ListPersonBusinessLogic, ListPersonDataStore {
    
    var presenter: ListPersonPresentationLogic?
    var worker: ListPersonWorker?
    
    var people: [Person]?
    
    //MARK: Do something
    func fetchPeople(request: ListPeople.FetchPeople.Request) {
        worker = ListPersonWorker()
        
        worker?.fetchPeople(completion: { people in
            self.people = people
            let response = ListPeople.FetchPeople.Response(people: people)
            self.presenter?.presentFetchedPeople(response: response)
        })
    }
    
}
